# coding: utf-8
module WorkEnvs
    # Class to store all the dependencies of an env
    #
    # It provides helpers to convert between version names and sha1
    #
    # Dependencies can come from multiple sources
    # - rev_files
    # - --sha1, --sub-sha1 options
    # - --version option
    # - Package (RPM, Deb) dependencies
    #
    # Dependencies from env to its version (and its subEnv versions) are stored
    # as depInfo hash:
    #
    #  { :sha1 => <sha1>, :version => <version> }
    class Dependencies
        # Mark the environment as partial. (default = false)
        #
        # It means that it is OK for some environment class
        # from the env dependency tree to not have any dep_info to them
        attr_accessor :partialEnv

        # Flag enable by setting WENV_IGNORE_CONFLICTS (default = nil)
        #
        # Ignore if a dep_info is pushed to an envClass is different from
        # a previous dep_info pushed for the same envClass
        # In this case, the first on is kept.
        #
        # SEROUSLY DANGEROUS ! DON'T USE IT UNLESS YOU KNOW WHAT YOU'RE DOING !!!
        attr_reader :ignore_conflicts

        # Pointer to a PackageDownloader used to convert version and SHA1 (default = nil)
        attr_accessor :downloader

        # Hash of dep_infos (default = {})
        attr_reader :deps

        # Array of fields to query in the package DB
        FIELDS = [ :sha1, :version ]

        # Default constructor
        def initialize
            @deps = {}
            @partialEnv = false
            @ignore_conflicts = nil
            @ignore_conflicts = true if ENV["WENV_IGNORE_CONFLICTS"].to_s != ""
            @downloader = nil
        end

        # Internal function to add a dependency to deps
        #
        # - env is either the envType or an envClass
        # - dInfos is a dep_info hash generated by PackageDownloader
        #
        # Returns:
        # - true on success
        # - false on failure if @ignore_conflicts == true
        # Throws an exception on failure if @ignore_conflicts != true
        def _push(env, dInfos)
            name = (env.kind_of? Symbol) ? env : WorkEnvs::getEnvType(env)

            WorkEnvs::dputs("Deps[#{name}] <= (#{dInfos.to_s})")

            FIELDS.each(){|f|
                raise("Incomplete dependency #{dInfos}. '#{f.to_s}' field is missing") if dInfos[f] == nil
            }

            if @deps[name] != nil then
                if @deps[name] != dInfos then
                     return false if @ignore_conflicts == true

                     raise("Invalid dependencies for #{name}.\nRequire for #{name.to_s} both:\n"+
                           "\t* '#{@deps[name].to_s}'\n\t* '#{dInfos.to_s}' ")
                end
            end
            @deps[name] = dInfos
            return true
        end
        private :_push

        # Convert an (envType, sha1) couple to a dep_info and add it to deps using #_push
        #
        # env is either the envType or an envClass
        #
        # Return _push result or false if required == false and no matching SHA1 was found
        # in the DB
        #
        # Throws EmptyQueryException if required == true and no match was found
        def push_sha1(env, sha1, required = true)
            return false if sha1.to_s == ""
            #SHA1 but no version
            dInfos = @downloader.queryDepInfosFromSHA1(env, sha1, required)
            return false if dInfos == nil
            return _push(env, dInfos)
        end

        # Convert an (envType, version) couple to a dep_info and add it to deps using #_push
        #
        # env is either the envType or an envClass
        #
        # Return _push result or false if required == false and no matching version was found
        # in the DB
        #
        # Throws EmptyQueryException if required == true and no match was found
        def push_version(env, version, required = true)
            return false if version.to_s == ""

            #SHA1 but no version
            dInfos = @downloader.queryDepInfosFromVersion(env, version, required)
            return false if dInfos == nil
            return _push(env, dInfos)
        end

        # Convert an (envType, package full name) couple to a dep_info and add it to deps using #_push
        #
        # env is either the envType or an envClass
        #
        # Return _push result or false if required == false and no matching package was found
        # in the DB
        #
        # Throws EmptyQueryException if required == true and no match was found
        def push_name(env, pName, required = true)
            dInfos = @downloader.queryDepInfosFromName(env, pName, required)
            return false if dInfos == nil
            return _push(env, dInfos)
        end

        # Return if there is a dep_into to the envType name
        def exists?(name)
            return @deps[name] != nil
        end

        # Remove (if any) the dep_into to the envType name
        def del(name)
            return @deps[name] = nil
        end

        # Get the required version string for envType name
        def get_version(name)
            return nil if @deps[name] == nil
            return @deps[name][:version]
        end

        # Get the required SHA1 string for envType name
        def get_sha1(name)
            return nil if @deps[name] == nil
            return @deps[name][:sha1]
        end

        # Iterator on dep_infos
        #
        # Block args are (envType, dep_info)
        def each()
            @deps.each(){|name, h|
                yield name, h
            }
        end

        # Generates a string with a human reable list of all dep_infos
        def to_s
            str = ""
            @deps.each(){|name, h|
                str+= "\t" + name.to_s.ljust(20) + "=> " + h[:version].to_s + " (" + h[:sha1].to_s + ")\n"
            }
            return str
        end

        # Returns true if there is no dep_info
        def empty?
            return @deps.empty?
        end

        # Compare two Dependencies
        #
        # This make sure all dep_infos are the sames in the two
        def ==(another)
            begin
                @deps.each(){|name, h|
                    return false if another.deps[name] != h
                }
                another.each(){|name, h|
                    return false if @deps[name] != h
                }
                return true
            rescue => e
                return false
            end
        end

        # Concat another Dependencies object into this one
        #
        # Throws exception if both are incompatible
        def concat(another)
            if another != nil then
                another.each(){|name, h|
                    _push(name, h)
                }
                if another.partialEnv == true
                    @partialEnv = true
                end
            end
            return self
        end
    end
end
